import Head from 'next/head'

import Header from "@/pages/components/layouts/header";
import Loader from "@/pages/components/layouts/loader";
import Footer from "@/pages/components/layouts/footer";
import {useExternalScript} from "@/pages/utils/load-external-script";
import PostList from "@/pages/components/posts/list";
import axios from "axios";
import {InferGetStaticPropsType} from "next";

export async function getStaticProps() {
    let data: any = null;
    try {
        const res = await axios.get('http://127.0.0.1:3000/app/posts', {headers: {origin: 'http://127.0.0.1:4000'}})
        data = await res.data;
    } catch (e) {
        console.log(e);
        data = null;
    }

    return {
        props: {
            posts: data,
        },
    }
}
interface HomePageProps {
    posts: any[];
}

const ReadyView = ({posts}: HomePageProps) => {
    return (
        <>
            <Head>
                <title>Abstract</title>
                <link rel="icon" href="/favicon.ico"/>
                <meta name="author" content=""/>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>

                <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"/>
                <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"/>
                <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png"/>
            </Head>
            <main>
                <Header></Header>
                <PostList posts={posts}></PostList>
                <Footer></Footer>
            </main>
        </>
    );
}

export default function Home({posts}: InferGetStaticPropsType<typeof getStaticProps>) {
    const state = useExternalScript(true);
    return (
        <>
            {state === "loading" && <Loader></Loader>}
            {state === "ready" && <ReadyView posts={posts}></ReadyView>}
        </>
    )
}