import Head from 'next/head'

import Header from "@/pages/components/layouts/header";
import Loader from "@/pages/components/layouts/loader";
import Footer from "@/pages/components/layouts/footer";
import {useExternalScript} from "@/pages/utils/load-external-script";
import PostList from "@/pages/components/posts/list";
import Api from "@/pages/libs/api";
import {GetStaticProps} from "next";

const ReadyView = ({posts = [], sliders = []}: any) => {
    return (
        <>
            <Head>
                <title>Abstract</title>
                <link rel="icon" href="/favicon.ico"/>
                <meta name="author" content=""/>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>

                <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"/>
                <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"/>
                <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png"/>
            </Head>
            <main>
                <Header></Header>
                <PostList posts={posts} sliders={sliders}></PostList>
                <Footer></Footer>
            </main>
        </>
    );
}

export const getStaticProps: GetStaticProps = async (context) => {
    const resPosts = await Api.getPosts();
    const posts = resPosts.data;

    const resSliders = await Api.getSliders();
    const sliders = resSliders.data;

    return {
        props: {
            posts,
            sliders
        },
        revalidate: 10,
    };
};

export default function Home({posts, sliders}: any) {
    const state = useExternalScript(true);
    return (
        <>
            {state === "loading" && <Loader></Loader>}
            {state === "ready" && <ReadyView posts={posts} sliders={sliders}></ReadyView>}
        </>
    )
}