import React from "react";
import Head from "next/head";
import Header from "@/components/layouts/header";
import Footer from "@/components/layouts/footer";
import {useExternalScript} from "@/utils/load-external-script";
import Loader from "@/components/layouts/loader";

interface MainTemplateProps {
    children: React.ReactNode;
    head?: any;
    options?: any;
}

export default function Main({children, head, options}: MainTemplateProps) {
    const state = useExternalScript(true);
    return (
        <>
            {state === "loading" && <Loader></Loader>}
            {state === "ready" &&
                <>
                    <Head>
                        <title>Abstract</title>
                        <link rel="icon" href="/favicon.ico"/>
                        <meta name="author" content=""/>
                        <meta name="description" content="Generated by create next app"/>
                        <meta name="viewport" content="width=device-width, initial-scale=1"/>

                        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"/>
                        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"/>
                        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png"/>
                    </Head>
                    <main>
                        <Header></Header>
                        {children}
                        <Footer></Footer>
                    </main>
                </>
            }
        </>
    )
}

